server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: 2112
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  cloud:
    aws:
      region:
        static: ap-northeast-1   # <--- set to your bucket region
      # Omit credentials below if you use env vars/instance profile (recommended)
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:}
        secret-key: ${AWS_SECRET_ACCESS_KEY:}
      s3:
        region: ap-northeast-1   # optional
app:
  s3:
    bucket: your-bucket-name
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka